<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dao</string>
	</array>
	<key>name</key>
	<string>Daoyu</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>IDLES|[.]</string>
			<key>name</key>
			<string>constant.numeric.symbol.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>UPLEV|DELEV|[&lt;&gt;]</string>
			<key>name</key>
			<string>string.quoted.single.symbol.level.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[()\[\]]|HALVE|MERGE|SPLIT</string>
			<key>name</key>
			<string>string.symbol.movement.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[!;]|SWAPS|INPUT</string>
			<key>name</key>
			<string>keyword.symbol.data.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[#%]|EXECS|SIFTS</string>
			<key>name</key>
			<string>constant.character.escape.symbol.linear.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[*=]|POLAR|EQUAL</string>
			<key>name</key>
			<string>entity.other.inherited-class.symbol.flow.restrict.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[/]|LATER</string>
			<key>name</key>
			<string>variable.parameter.symbol.bracket.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>S|DEALC</string>
			<key>name</key>
			<string>keyword.symbol.memory.restrict.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[$:]|DOALC|READS</string>
			<key>name</key>
			<string>entity.name.function.symbol.memory.permit.dao</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@.*</string>
			<key>name</key>
			<string>comment.line.dao</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dao</string>
	<key>uuid</key>
	<string>53a8ffbe-c696-494a-983d-05faf16842c7</string>
</dict>
</plist>
